Update FakeIP addresses and Ports
openBackhaul/ExecutionAndTraceLog pull request #117
Opened 2022-12-05 11:13 UTC by kmohr-soprasteria

Fixes #114

2022-12-05 14:14 UTC, IswaryaaS requested changes

2022-12-05 14:14 UTC, IswaryaaS commented on ExecutionAndTraceLog+services.yaml
> +      ip-address: 1.1.3.3
eatl to be updated to address and port of v2.0.0

2022-12-05 15:27 UTC, openBackhaul commented on ExecutionAndTraceLog.yaml
> +                stringified-response: '{"current-controller": "1.1.4.1:8443"}'
Please, update according to fake-ip-address list.
If CurrentController would need a special Port, it would be filled-in by script.

2022-12-06 10:27 UTC, IswaryaaS requested changes

2022-12-06 10:27 UTC, IswaryaaS commented on ExecutionAndTraceLog+config.json
> +                        "ipv-4-address": "1.1.3.11"
ol is of version 1.0.0 and its corresponding ip and port needs to be updated accordingly.

2022-12-06 10:27 UTC, IswaryaaS commented on ExecutionAndTraceLog+config.json
> +                        "ipv-4-address": "1.1.3.12"
Similar to above comment, the proceeding occurrences of aa, alt, okm are also of version 1.0.0, but they have ip-address and port mapped as per v2.0.0.

2022-12-06 10:27 UTC, IswaryaaS commented on ExecutionAndTraceLog+services.yaml
> +      tcp-port: 3005
port for ALT v1.0.0 is 3006 as per fake-ip-table. But it is somehow mistaken as 3005 which needs to be updated

2022-12-06 10:37 UTC, kmohr-soprasteria commented on ExecutionAndTraceLog+config.json
> +                        "ipv-4-address": "1.1.3.11"
updated

2022-12-06 10:55 UTC, IswaryaaS approved these changes

2022-12-06 12:48 UTC, merged