issue-163 : implemented OAM service methods
openBackhaul/ExecutionAndTraceLog pull request #169
Opened 2023-01-17 09:21 UTC by DanaSunal

Fixes #163

2023-01-17 09:24 UTC, DanaSunal commented
Reviewer is @vanithavalluripalli9

2023-01-18 15:16 UTC, vanithavalluripalli9 requested changes
Please automate forwardings to ALT for the PUT operations of HttpClient , TcpClient , OperationClient , TcpServer , HttpServer , OperationServer as we are updating them.

2023-01-18 15:16 UTC, vanithavalluripalli9 commented on server/service/HttpClientService.js
> +      await fileOperation.writeToDatabaseAsync(url, body, false);
Please add forwarding automation to ALT

2023-01-24 15:04 UTC, DanaSunal commented on server/service/HttpClientService.js
> +      await fileOperation.writeToDatabaseAsync(url, body, false);
Done.

2023-01-24 15:18 UTC, merged