issue-102 : Support Version 2.0.0 changes for regard-application
openBackhaul/ExecutionAndTraceLog pull request #173
Opened 2023-01-23 10:36 UTC by DanaSunal

Fixes #92 #99 #100 #101 #102 #124

Signed-off-by: Dana Sunalova <dana@paxet.io>

2023-01-23 10:37 UTC, DanaSunal commented
Reviewer is @vanithavalluripalli9

2023-01-24 11:12 UTC, vanithavalluripalli9 requested changes

2023-01-24 11:12 UTC, vanithavalluripalli9 commented on server/service/individualServices/PrepareForwardingAutomation.js
> +            redirectServiceRequestRequestBody.serviceLogOperation = serviceLogOperation;
service log operation should be /v1/record-service-request

2023-01-24 15:04 UTC, DanaSunal commented on server/service/individualServices/PrepareForwardingAutomation.js
> +            redirectServiceRequestRequestBody.serviceLogOperation = serviceLogOperation;
Done, thanks for spotting.

2023-01-24 16:17 UTC, vanithavalluripalli9 requested changes

2023-01-24 16:17 UTC, vanithavalluripalli9 commented on server/service/individualServices/PrepareForwardingAutomation.js
> +            redirectServiceRequestRequestBody.serviceLogOperation = await getOperationClientToLogServiceRequestAsync();
Can we get the the service log operation from operation server as specified in OAS  instead of operationClient as operationClient is configurable and subject to changes

2023-01-25 08:35 UTC, DanaSunal commented on server/service/individualServices/PrepareForwardingAutomation.js
> +            redirectServiceRequestRequestBody.serviceLogOperation = await getOperationClientToLogServiceRequestAsync();
Done.

2023-01-31 12:23 UTC, vanithavalluripalli9 approved these changes
Approved.

2023-01-31 12:23 UTC, merged