issue-98 : support v2.0.0 for bequeath-your-data-and-die
openBackhaul/ExecutionAndTraceLog pull request #185
Opened 2023-01-30 08:56 UTC by DanaSunal

- removed app name check
- NewRelease LTP is now traced from PromptForBequeathingDataCausesTransferOfListOfApplications
- switch to findAndUpdateApplicationInformationAsync

Fixes #98, #94

- added protocol support for callbacks

Fixes #95

- updated callbacks to include new application name and updated request body if needed

Fixes #96

Signed-off-by: Dana Sunalova <dana@paxet.io>

2023-01-30 08:56 UTC, DanaSunal commented
Reviewer is @vanithavalluripalli9

2023-01-31 13:38 UTC, vanithavalluripalli9 requested changes

2023-01-31 13:38 UTC, vanithavalluripalli9 commented on server/service/IndividualServicesService.js
> +      let fcPort = fcPorts.find(fcp => fcp[onfAttributes.FC_PORT.PORT_DIRECTION] === FcPort.portDirectionEnum.OUTPUT);
can we declare a function to fetch new release uuid to improve code readability.

2023-02-01 05:22 UTC, vanithavalluripalli9 requested changes

2023-02-01 05:22 UTC, vanithavalluripalli9 commented on server/service/IndividualServicesService.js
> +      if (isUpdatedAppName || isUpdatedReleaseNumber) {
According to my understanding , If we are trying to send bequeath-your-data-and-die for application of same version but running in different ip-address and port then this will not work . Please correct me if mmmmy understanding is wrong . If not can you please update the logic accordingly.

2023-02-01 09:24 UTC, DanaSunal commented on server/service/IndividualServicesService.js
> +      if (isUpdatedAppName || isUpdatedReleaseNumber) {
Hi Vanitha, there was no change to this logic from my side, this was the way how it was previously done. My understanding is, that for IP address/port change we do not need to call findAndUpdateApplicationInformationAsync. Software upgrade will still happen, that is outside the condition. Please let me know if I should also remove these conditions.

2023-02-01 13:22 UTC, vanithavalluripalli9 commented on server/service/IndividualServicesService.js
> +      if (isUpdatedAppName || isUpdatedReleaseNumber) {
Hi Dana , your understanding is correct instead of calling findAndUpdateApplicationInformationAsync , we can directly set the ipaddress and port of New release  as we are setting the application name, so that the data transfer will happen to the new release appropriately.
Sorry , for wrong description in issue will update it .

2023-02-01 13:58 UTC, DanaSunal commented on server/service/IndividualServicesService.js
> +      let fcPort = fcPorts.find(fcp => fcp[onfAttributes.FC_PORT.PORT_DIRECTION] === FcPort.portDirectionEnum.OUTPUT);
Done.

2023-02-06 16:51 UTC, vanithavalluripalli9 approved these changes
Approved.

2023-02-06 16:51 UTC, merged