AP-697 : use new returned headers from register-yourself
openBackhaul/ExecutionAndTraceLog pull request #237
Opened 2023-05-26 06:56 UTC by DanaSunal

2023-05-26 06:57 UTC, DanaSunal commented
Relates to openBackhaul/ApplicationPattern#697 
Reviewer is @PrathibaJee

2023-05-29 16:17 UTC, PrathibaJee requested changes

2023-05-29 16:17 UTC, PrathibaJee commented on server/controllers/BasicServices.js
> +      originator, req.url, responseCode, req.body, responseBodyToDocument);
Also originator needs to be changed based on the returned value. Otherwise , incase of the "no requestbody" , originator will hold the xcorrelator information.

2023-05-29 16:17 UTC, PrathibaJee commented on server/controllers/BasicServices.js
>        .catch(async function (response) {
Variable "response" needs to be changed to "responseBody"

2023-05-29 16:17 UTC, PrathibaJee commented on server/controllers/BasicServices.js
>    } catch (error) {}
Overall , I have a suggestion that instead of getting the header information from the "basicservices" , shall we identify this here in the controller itself and use it further ?
Because , if there is a failure due to logical error in the basic services , then we may not get the headers in the return value , and endup in further exception.

2023-05-30 13:13 UTC, DanaSunal commented on server/controllers/BasicServices.js
> +      originator, req.url, responseCode, req.body, responseBodyToDocument);
Originator does not change in basicServices/registerYourself in the original code. What value should it hold?

2023-05-30 13:14 UTC, DanaSunal commented on server/controllers/BasicServices.js
>        .catch(async function (response) {
I do not see a variable called 'response'.

2023-05-30 13:16 UTC, DanaSunal commented on server/controllers/BasicServices.js
>    } catch (error) {}
Agreed.

2023-06-01 06:54 UTC, PrathibaJee approved these changes
Thanks for fixing the review comments.

2023-06-01 06:54 UTC, merged