Resolve Proposal to use the 'getAllApplicationList' method to from ApplicationPattern
openBackhaul/ExecutionAndTraceLog pull request #249
Opened 2023-06-07 06:35 UTC by ManasaBM1

Fixes #248

2023-06-20 14:33 UTC, DanaSunal requested changes

2023-06-20 14:33 UTC, DanaSunal commented on server/service/individualServices/SoftwareUpgrade.js
> +                let newReleaseTcpClientUuid = (await logicalTerminationPoint.getServerLtpListAsync(newReleaseUuid));
This does not look correct. getServerLtpListAsync always returns a list, why was this change made? Same for all changes below.

2023-06-21 04:46 UTC, ManasaBM1 commented on server/service/individualServices/SoftwareUpgrade.js
> +                let newReleaseTcpClientUuid = (await logicalTerminationPoint.getServerLtpListAsync(newReleaseUuid));
make the previous changes  since this changes is not correct

2023-06-22 11:21 UTC, DanaSunal approved these changes

2023-06-22 11:21 UTC, merged