Resolve the  isDataTransferRequired  check from /v1/bequeath-your-data-and-die implementation as it effects service idempotence concept
openBackhaul/ExecutionAndTraceLog pull request #261
Opened 2023-06-16 04:12 UTC by ManasaBM1

Fixes #256

2023-06-16 04:41 UTC, ManasaBM1 commented
Reviewer is @DanaSunal

2023-06-19 08:11 UTC, DanaSunal approved these changes

2023-06-19 08:13 UTC, DanaSunal requested changes
softwareUpgrade will be missing a parameter after isDataTransferRequired variable is removed. See line 123.

2023-06-21 04:23 UTC, ManasaBM1 commented
> softwareUpgrade will be missing a parameter after isDataTransferRequired variable is removed. See line 123.

Done Adding the isDataTransferRequired  Variable

2023-06-22 11:25 UTC, DanaSunal approved these changes

2023-06-22 11:25 UTC, merged