issue-281 : added 400 Error message for unsupported HTTPS
openBackhaul/ExecutionAndTraceLog pull request #288
Opened 2023-07-05 11:41 UTC by DanaSunal

Fixes #281

2023-08-05 12:43 UTC, PrathibaJee requested changes

2023-08-05 12:43 UTC, PrathibaJee commented on server/service/IndividualServicesService.js
> +      if (body['protocol'] === "HTTPS") {
The problem mentioned in this issue is not related to restrict “HTTPS” protocol.
As per the specification , both HTTP and HTTPS are supported.
 
![image](https://github.com/openBackhaul/ExecutionAndTraceLog/assets/62344562/dd3c2d18-4473-4854-9fd0-96337f6cca73)


I think , the scenario and ask is , 
An application is running in http://1.1.1.1:3000/
But , while regarding that application , if the http-client protocol is provided as “HTTPS” instead of “HTTP” then 
The client will try to reach the server using the url https://1.1.1.1:3000/

In such case , REST client will receive an Error “EPROTO” and the subsequent code in the client side marks the response code as 500 and further recording the service record to EATL application.
If this scenario is already handled in this PR https://github.com/openBackhaul/ApplicationPattern/pull/802 , we shall close this PR and the issue.

2023-08-06 07:33 UTC, DanaSunal commented on server/service/IndividualServicesService.js
> +      if (body['protocol'] === "HTTPS") {
That scenario you described is handled by openBackhaul/ApplicationPattern#802. Thank you for the explanation, feel free to close it.

2023-08-06 18:21 UTC, PrathibaJee commented on server/service/IndividualServicesService.js
> +      if (body['protocol'] === "HTTPS") {
Thanks Dana. I will close this PR and the issue.

2023-08-06 18:21 UTC, closed without merging