change forwarding name for list of applications service
openBackhaul/ExecutionAndTraceLog pull request #354
Opened 2024-05-13 06:21 UTC by at00825957

change forwarding name for list of applications service

2024-05-23 12:00 UTC, IswaryaaS commented on server/service/individualServices/PrepareRegardApplication.js
> +                let forwardingKindName = "RegardApplicationCausesSequenceForInquiringServiceRecords.RequestForInquiringServiceRecords";
It is really great job moving the services related to regardApplication to a dedicated file. 
Also, since it is not preparing the regardApplication but it is doing actual process of regardApplication, kindly requesting you to change the file name.

2024-05-23 12:02 UTC, IswaryaaS commented on server/service/individualServices/PrepareRegardApplication.js
> +                let forwardingKindName = "RegardApplicationCausesSequenceForInquiringServiceRecords.RequestForInquiringServiceRecords";
Also, please list down the changes made in the PR as we can see multiple changes are made apart from the descriptions mentioned. So, this can help us reviewing the  list of changes made

2024-05-24 12:00 UTC, at00825957 commented on server/service/individualServices/PrepareRegardApplication.js
> +                let forwardingKindName = "RegardApplicationCausesSequenceForInquiringServiceRecords.RequestForInquiringServiceRecords";
Done

2024-05-28 10:37 UTC, PrathibaJee approved these changes

2024-05-28 12:28 UTC, PrathibaJee requested changes

2024-05-28 12:28 UTC, PrathibaJee commented on server/service/IndividualServicesService.js
> +const PrepareRegardApplication = require('./individualServices/PrepareRegardApplication');
Modify the filename as expected ,
```
const PrepareRegardApplication = require('./individualServices/RegardApplication');
```

2024-05-28 12:57 UTC, at00825957 commented on server/service/IndividualServicesService.js
> +const PrepareRegardApplication = require('./individualServices/PrepareRegardApplication');
Done

2024-06-03 13:10 UTC, PrathibaJee approved these changes

2024-06-04 05:48 UTC, IswaryaaS approved these changes

2024-06-04 05:49 UTC, merged