Update UUIDs of Services
openBackhaul/ExecutionAndTraceLog pull request #73
Opened 2022-11-15 17:36 UTC by openBackhaul

**Process for updating the UUIDs of Services**
- [x] Thorsten to check categories of OperationServers and OperationClients in ServiceList
- [x] Iswaryaa to review categories of OperationServers and OperationClients in ServiceList
- [ ] Katharina to add new UUIDs based on category of operation (but not old UUID) in ServiceList
- [ ] Iswaryaa to review new UUIDs in ServiceList
- [ ] Katharina to CTRL+h for old UUIDs and replace them by new UUIDs in ForwardingList, CONFIGfile and OAS.
- [ ] Katharina to step through ForwardingList, CONFIGfile and OAS and compare every UUID against new one in ServiceList
- [ ] Iswaryaa to review new UUIDs in ForwardingList, CONFIGfile and OAS
If no errors found
- [ ] Iswaryaa to delete old UUIDs in ServiceList
- [ ] Iswaryaa to merge the feature branch into develop
- [ ] Iswaryaa to close this issue and delete the feature branch on GitHub

2022-11-17 05:58 UTC, IswaryaaS commented
services.yaml file looks good for new uuid updates. We can proceed updating other files new uuid(s) now

2022-11-17 12:34 UTC, kmohr-soprasteria commented
updated uuids according to mapping table provided in issue:
- config file: no entries related to no longer used found
- forwardings file: no updates
- oas: updates added, no entries related to no longer used found

2022-11-17 12:56 UTC, kmohr-soprasteria commented
no changes required in fowardings; mapping table attached to issue #71

2022-11-20 14:02 UTC, IswaryaaS requested changes

2022-11-20 14:02 UTC, IswaryaaS commented on ExecutionAndTraceLog+services.yaml
> +  title: ExecutionAndTraceLog
Somehow this file got replaced by ExecutionAndTraceLog.yaml . Requesting you to check and replace it with service.yaml file

2022-11-21 11:59 UTC, kmohr-soprasteria commented on ExecutionAndTraceLog+services.yaml
> +  title: ExecutionAndTraceLog
restored the correct file contents, ready for review

2022-11-21 12:48 UTC, merged