Update Profiles
openBackhaul/ExecutionAndTraceLog pull request #85
Opened 2022-11-22 11:22 UTC by openBackhaul

See issue #74

Fixes issue #74

2022-11-22 12:04 UTC, openBackhaul commented
Callback PromptForBequeathingDataCausesTransferOfListOfApplications should not been deleted.

2022-11-23 06:29 UTC, IswaryaaS requested changes

2022-11-23 06:29 UTC, IswaryaaS commented on ExecutionAndTraceLog.yaml
> +          url: #[/core-model-1-4:control-construct/logical-termination-point=eatl-2-0-0-tcp-c-*/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/r
In callback uri path of ApprovedApplicationCausesRequestForServiceRequestInformation (line 926), can we update the static reference of service /v1/redirect-service-request-information with a path reference. Like, we can have "[/core-model-1-4:control-construct/logical-termination-point=eatl-2-0-0-op-c-im-*-*-*-*-000/layer-protocol=0/operation-client-interface-1-0:operation-client-interface-pac/operation-client-interface-configuration/operation-name]"

2022-11-23 06:29 UTC, IswaryaaS commented on ExecutionAndTraceLog.yaml
> +                      properties:
As per my understanding, providing more than one attribute (either ip-address or domain-name) might lead to confusion on which should be taken for procedence. So, we usually avoid a condition of having both ip-address and domain-name to be produced or accepted. (please correct me if I am wrong). 
In /v1/list-applications, the given schema would allow both ip-address and domain-name to be produced in response-body (eventhough they are not mentioned as required, there might be a possibility to pick both since we donot have restriction that only one among the two is allowed).
If my understanding is correct, can we add additional restrictions like
                        address:
                            type: object
                            minProperties: 1
                            maxProperties: 1
                            additionalProperties: false
                            properties:
                              ip-address:
                                type: object
                                minProperties: 1
                                additionalProperties: false
                                properties:
                                  ipv-4-address:
                                    type: string
                              domain-name:
                                type: string

2022-11-23 06:29 UTC, IswaryaaS commented on ExecutionAndTraceLog.yaml
> +              description: 'update elasticsearch'
Just an idea:
In services like /v1/record-service-request, /v1/list-records, /v1/list-records-of-flow, /v1/list-records-of-unsuccessful, we have descriptions pointing to ElasticSearch like "update elastic search", "from elastic search" etc., 
Since we have http-c, tcp-c and es-c clients for elasticsearch, can we add more detailed descriptions using the path pointing to elastic search clients address, port and index. 
Please let me know your views

2022-11-23 08:12 UTC, openBackhaul commented on ExecutionAndTraceLog.yaml
> +                    find or create [/core-model-1-4:control-construct/logical-termination-point=eatl-2-0-0-http-c-bm-nr-1-0-0-000/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/
Changed as proposed.
e.g. eatl-2-0-0-tcp-c-bm-nr-1-0-0-000 => eatl-2-0-0-tcp-c-im-nr-2-0-0-000

2022-11-23 08:20 UTC, openBackhaul commented on ExecutionAndTraceLog.yaml
> +          url: #[/core-model-1-4:control-construct/logical-termination-point=eatl-2-0-0-tcp-c-bm-nr-2-0-0-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-c
Changed as proposed.
e.g. eatl-2-0-0-tcp-c-bm-nr-1-0-0-000 => eatl-2-0-0-tcp-c-im-nr-2-0-0-000

2022-11-23 08:26 UTC, openBackhaul commented on ExecutionAndTraceLog.yaml
> +                            from [/core-model-1-4:control-construct/logical-termination-point=eatl-1-0-0-http-c-*/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/http-client-inte
OAS: Now, CTRL+f for "-1-0-0-" results in a single finding ("eatl-2-0-0-http-c-bm-or-1-0-0-000") and that should be fine.
OAS: Now, CTRL+f for "1.0.0" results in 5 findings, which should also be fine.

2022-11-23 08:27 UTC, openBackhaul commented on ExecutionAndTraceLog.yaml
> +                            from [/core-model-1-4:control-construct/logical-termination-point=eatl-2-0-0-http-c-im-nr-1-0-0-000/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/ht
Changed as proposed.

2022-11-23 08:28 UTC, openBackhaul commented on ExecutionAndTraceLog.yaml
> +                            from [/core-model-1-4:control-construct/logical-termination-point=eatl-2-0-0-http-c-bm-nr-1-0-0-000/layer-protocol=0/http-client-interface-1-0:http-client-interface-pac/ht
Changed as proposed.

2022-11-23 08:34 UTC, openBackhaul commented on ExecutionAndTraceLog.yaml
> +                      properties:
/v1/list-applications is for reading data from the application.
The target of having either IP address or domain name has to be reached on the ingress, means: while writing into the application.
If we don't facilitate listing both on the egress, we couldn't identify ambiguity in the data.
So, no min-, max-, pattern or enum on the egress.

2022-11-23 08:42 UTC, openBackhaul commented on ExecutionAndTraceLog.yaml
> +          url: #[/core-model-1-4:control-construct/logical-termination-point=eatl-2-0-0-tcp-c-*/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/r
Searching the ServiceList for occurrences of "eatl-2-0-0-op-c-im-tar-1-0-0-000" results in 8 clients.
The first two are:
- eatl-2-0-0-op-c-im-ro-2-0-0-004
- eatl-2-0-0-op-c-im-tar-1-0-0-000
Means a reference would look like:
- eatl-2-0-0-op-c-im-*-*-*-*-*
This is obviously not very meaningful.
So, I decided for the concrete operation name despite it might change in future.

2022-11-23 08:51 UTC, openBackhaul commented on ExecutionAndTraceLog.yaml
> +              description: 'update elasticsearch'
The descriptions are made for giving exact guidance about where to write or read the value of some service's attributes.  
Because we agreed that the structure of data inside the database or LOADfile shall be encapsulated inside the application, I would not know where to point inside the database or LOADfile.  
Describing the exact http-c, tcp-c and es-c clients for elasticsearch would only make sense, if there would be multiple instances be used in parallel, which is not the case.
Consequently, I would like to avoid the additional effort for describing and maintaining these clients.

2022-11-23 11:33 UTC, IswaryaaS requested changes

2022-11-23 11:33 UTC, IswaryaaS commented on ExecutionAndTraceLog.yaml
> +                            minProperties: 1
As per comment, https://github.com/openBackhaul/ExecutionAndTraceLog/pull/85#discussion_r1030150602, since we will use $ref: '#/components/schemas/logicalTerminationPoint' in egress situations, can we also remove maxProperties:1 constraint for tcp-client / remote-address. Kindly correct me if I am wrong.

2022-11-23 13:27 UTC, IswaryaaS commented on ExecutionAndTraceLog.yaml
> +                            minProperties: 1
Just now got the clarification
"“If a domain-name is added via a service(for example for v1/redirect-service-request-information) , then the server-side code will include the attributes required for including domain-name along with the values and delete the ip-address attribute at the same time.”. Based on this decision , my comment will become obsolete. 
Apart from this every other changes looks fine. So, approving the PR

2022-11-23 13:27 UTC, IswaryaaS approved these changes

2022-11-24 08:56 UTC, merged